<script>
  import * as Icon from '$lib';
  const random_hex_color_code = () => {
    let n = (Math.random() * 0xfffff * 1000000).toString(16);
    return '#' + n.slice(0, 6);
  };
</script>

<div class="flex flex-wrap p-3">
  <Icon.A1C size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.A1CAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.A3DModel size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.A3DSMax size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.A4D size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ABAP size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ABIF size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AGC size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AMD size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AMPL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ANTLR size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.APIBlueprint size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.APIExtractor size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.APL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.APLOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.APlus size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ARM size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ATS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ATT size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AVR size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Acre size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ActionScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Ada size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Adobe size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeAcrobat size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeAfterEffects size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeAnimate size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeAudition size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeBridge size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeCharacterAnimator size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeCreativeCloud size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeDimension size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeDreamweaver size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeFlash size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeFuse size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeIllustrator size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeInCopy size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeInDesign size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeLightroom size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeMediaEncoder size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobePhotoshop size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobePrelude size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobePremiere size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobePremiereRush size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdobeXD size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AdonisJS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Aeternity size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AffectScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AffinityDesigner size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Agda size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Akka size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Alacritty size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AlacrittyAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Alex size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Alloy size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AlpineLinux size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AmigaOS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AmuseWiki size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Analytica size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AngelScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AnimeStudio size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Ansible size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AnsibleAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Antwar size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AnyScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ApacheANT size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Apollo size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Apple size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Appveyor size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Arc size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ArchLinux size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Arduino size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ArtText size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ArtText4 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AsciiDoc size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Asciidoctor size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AssemblyAGC size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AssemblyAMD size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AssemblyARM size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AssemblyATT size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AssemblyAVR size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AssemblyGeneric size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AssemblyHitachi size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AssemblyIntel size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AssemblyMotorola size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AssemblyPowerPC size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AssemblyRISCV size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AssemblySPARC size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AssemblyVAX size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AssemblyZilog size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Asymptote size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AsymptoteAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Atoum size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Audacity size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Augeas size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Aurelia size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AutoHotkey size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AutoIt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Automator size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Avro size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Awk size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.AzurePipelines size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.BEM size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.BNF size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.BYOND size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Babel size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Ballerina size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Bazaar size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Bazel size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.BazelOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Behat size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.BibTeX size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Bikeshed size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Biml size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.BinTray size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Binder size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Bison size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.BitHound size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Blender size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.BlitzBasic size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Bloc size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Bluespec size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Boo size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Bors size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Bosque size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Brainfuck size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Brakeman size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Bro size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Broccoli size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Brotli size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.BrotliOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Browserslist size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Browsersync size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Brunch size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Buck size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.BuildBoot size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Buildkite size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Bundler size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CASC size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CDF size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CKEditor size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CLIPS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CNAB size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.COBOL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CPAN size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CPlusPlus size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CSharp size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CSharpScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CSound size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CURL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CVS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CWL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Cabal size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Caddy size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CaddyOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Caffe size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Caffe2 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Cairo size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Cake size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CakePHP size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CakePHPOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Cakefile size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Calva size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Carthage size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Ceylon size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Chai size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Chapel size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ChartJS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Cheetah3D size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Chef size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Chocolatey size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ChucK size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CircleCI size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Cirru size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Clarion size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Clean size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Click size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ClojureJS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ClosureTemplate size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CloudFoundry size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Cmake size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CoNLL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CocoaPods size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Codacy size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CodeClimate size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CodeKit size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CodeMeta size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CodeMirror size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CodeShip size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Codecov size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ColdFusion size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CommitLint size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Commitizen size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CommonLisp size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ComponentPascal size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Composer size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Conan size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Conda size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Config size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ConfigCoffeeScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ConfigGo size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ConfigHaskell size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ConfigJS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ConfigPerl size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ConfigPython size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ConfigReact size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ConfigRuby size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ConfigRust size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ConfigTypeScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Coq size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Cordova size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CorelDRAW size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CorelDRAWAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Coveralls size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CpcdosCPlus size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CraftTweaker size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Creole size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Crowdin size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Crystal size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Cubit size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Cucumber size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Cuneiform size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.CurlLang size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Curry size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Cython size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.D3 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.DBASE size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.DNA size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.DOM size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.DOSBox size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.DOSBoxAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.DVC size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Dafny size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.DarcsPatch size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Dashboard size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.DataWeave size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Default size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Delphi size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Deno size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Dependabot size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.DevContainer size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.DeviceTree size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Dhall size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Dia size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Diff size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Digdag size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.DocBook size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.DocPad size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Docker size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Doclets size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Docz size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Dogescript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.DoneJS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Dotenv size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Dotjs size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Doxygen size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.DragonflyBSD size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Dragula size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Draw_io size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Drone size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Dub size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.DyLib size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Dyalog size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.E size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.EC size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ECLiPSeLang size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.EJS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.EQ size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ESDoc size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ESLint size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ESLintOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Eagle size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.EasyBuild size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Ecere size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Edge size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.EditorConfig size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Eiffel size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Electron size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ElementaryOS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Elm size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Emacs size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Ember size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.EmberScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Ensime size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Expo size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.FBX size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.FFmpeg size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.FOSSA size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Fabfile size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Fabric size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Factor size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Falcon size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Fancy size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Fantom size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Fauna size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Faust size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Fexl size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Fiddle size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Figma size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.FinalDraft size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Finder size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Firebase size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.FirebaseBolt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Flask size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Floobits size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Flow size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Flutter size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Flux size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Font size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.FontBitmap size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.FontForge size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.FontOutline size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ForTheRecord size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Fork size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Fortran size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Fossil size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Fountain size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Franca size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.FreeDOS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.FreeDesktop size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.FreeMarker size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.FreeMat size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Frege size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.FtHTML size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.FuelUX size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.FuseBox size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Futhark size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GAMS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GAP size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GAUSS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GDB size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GF size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GIMP size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GN size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GNU size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Galaxy size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Galen size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GameMaker size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Gatsby size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GenStat size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Genshi size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Gentoo size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Ghostscript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GitLab size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Gitpod size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GlTF size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Glade size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Glide size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Glyphs size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Gnuplot size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Go size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GoOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GoReleaser size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Godot size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Golo size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Gosu size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Gradle size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GraphQL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GraphQLCodeGenerator size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GraphViz size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Grapher size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Graphite size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.GravitDesigner size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Greenkeeper size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Gridsome size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Groovy size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Grunt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Gulp size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.HIE size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.HJSON size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Hack size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Haml size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Harbour size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.HashiCorp size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Haxe size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.HaxeDevelop size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Helix size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.HewlettPackard size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Hitachi size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Homebrew size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Hop size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Hoplon size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Houdini size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.HoundCI size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Hugo size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Husky size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Hy size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Hygen size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Hyper size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ICU size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.IDL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.IGORPro size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.IcoMoon size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Idris size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Illumos size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Image size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Imba size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ImbaAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ImbaOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Imgbot size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.InfluxData size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Inform7 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Ink size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Inkscape size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.InnoSetup size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Intel size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Io size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Ioke size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.IonicProject size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Isabelle size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Istanbul size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.J size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.JSON1 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.JSON2 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.JSON5 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.JSONLD1 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.JSONLD2 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.JSX size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.JSXAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.JSXAtom size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Jade size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Jakefile size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Janet size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Jasmine size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Jenkins size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Jest size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Jinja size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Jison size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Jolie size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Jscpd size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Jsonnet size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Julia size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Junos size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Jupyter size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.KNIME size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.KOS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.KRL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Kaitai size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Karma size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Keybase size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Keynote size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Khronos size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.KiCad size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Kibo size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.KitchenCI size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Kivy size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Knockout size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Kotlin size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Kubernetes size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Kusto size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.KustoAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Kx size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.LFE size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.LGTM size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.LINQPad size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.LLVM size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.LOLCODE size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.LSL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.LaTeX size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.LabVIEW size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Laravel size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Lark size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Lasso size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Latino size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Leaflet size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Lean size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Lefthook size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.LefthookAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Leiningen size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Lektor size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Lerna size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Lex size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.LexAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Libuv size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.LightWave size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Lighthouse size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.LilyPond size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Lime size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Lisp size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.LiveScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Logtalk size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.LookML size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Lua size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MATLAB size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MDX size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MELPA size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MIRC size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MJML size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MSDOS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MacVim size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Macaulay2 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Magit size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Mako size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Manjaro size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Manpage size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Mapbox size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MarkdownLint size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Marko size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MathJax size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Mathematica size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Matroska size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Max size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Maya size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MediaWiki size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Mercurial size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Mercury size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Mermaid size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Meson size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MesonOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MetaPost size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Metal size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Meteor size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MicrosoftAccess size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MicrosoftExcel size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MicrosoftInfoPath size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MicrosoftLync size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MicrosoftOneNote size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MicrosoftOutlook size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MicrosoftPowerPoint size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MicrosoftProject size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MicrosoftPublisher size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MicrosoftVisio size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MicrosoftWord size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Minecraft size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MiniZinc size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Mint size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Mirah size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Miranda size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Mixin size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Mocha size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Modelica size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ModernWeb size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Modo size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Modula2 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Modula3 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Moho size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Moleculer size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Moment size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MomentTimezone size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Monkey size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Mono size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Monotone size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Motorola size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Moustache size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Mruby size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.MuPAD size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NASM size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NAnt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NDepend size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NEON size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NPM size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NPMOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NSIS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NSISOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NSRI size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NSRIAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NVIDIA size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NWScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NXC size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nano size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nanoc size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Neko size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nemerle size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Neo4J size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nessus size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NestJS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NetLinx size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NetLogo size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Netlify size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NewRelic size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NextJS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nextflow size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NgRx size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nginx size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nib size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nickle size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nightwatch size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nimble size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nimrod size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nintendo64 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nit size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nix size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nmap size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nodemon size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nokogiri size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nomad size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Noon size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Normalise size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NuGet size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nuclide size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NumPy size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.NumPyOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nunjucks size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nuxt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Nx size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OCaml size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OOC size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OS2 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OWL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Oberon size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ObjectiveJ size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Octave size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Odin size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Ogone size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OmniGraffle size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Opa size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OpenAPI size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OpenBSD size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OpenBSDAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OpenCL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OpenCV size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OpenEXR size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OpenGL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OpenIndiana size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OpenOffice size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OpenPolicyAgent size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OpenSolaris size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OpenStack size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OpenVMS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OpenVPN size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OpenZFS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OpensCAD size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.OrgMode size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Ox size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Oxygene size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Oz size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.P4 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PAWN size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PCD size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PHP size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PHPUnit size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PICO8 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PM2 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PNPM size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.POVRay size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PROS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Pan size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Papyrus size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Parrot size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Pascal size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Patch size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Patreon size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PegJS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Perl6 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Phalcon size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Phoenix size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PhotoRec size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PhraseApp size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Pickle size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PicoLisp size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Pike size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PineScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Pipenv size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Pkgsrc size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PlatformIO size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Pod size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PogoScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PointWise size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Polymer size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Pony size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PostCSS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PostScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PowerBuilder size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PowerPC size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PowerShell size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Precision size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Precommit size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Prettier size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Prisma size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Processing size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Progress size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ProgressOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Propeller size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Proselint size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Protractor size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Pug size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PugOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PullApprove size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Puppet size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Pure size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PureBasic size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PureScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PyPi size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.PyUp size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Pyret size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Pytest size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.QSharp size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.QT size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Qiskit size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.QlikView size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Quasar size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.R size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.RAML size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.RData size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.RDoc size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.REALbasic size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.RISCV size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.RSpec size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.RStudio size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Racket size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Rascal size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Razzle size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ReScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ReStructuredText size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ReactOS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ReadTheDocs size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Reason size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ReasonStudios size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ReasonStudiosAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Rebol size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Red size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.RedOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Redux size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Reek size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.RegEx size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Remark size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Renovate size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.RestQL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Rexx size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Rhino3D size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Ring size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Riot size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.RiotOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Rmarkdown size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.RobotFramework size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.RobotFrameworkOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Robots size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Rollup size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.RollupOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Rsync size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Rubocop size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.RubyGems size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SAC size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SAS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SBT size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SPARC size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SQF size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SQLite size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SVN size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Sage size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Sails size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SaltStack size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.San size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Sandbox size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Scheme size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Scilab size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Scilla size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Scratch size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Scrutinizer size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Self size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SemanticRelease size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Sentry size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Sequelize size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Serverless size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ServiceFabric size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ShadowCLJS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ShellCheck size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Shen size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Shipit size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Shippable size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Shopify size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Shuriken size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Sigils size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SiliconGraphics size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SilverStripe size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Sinatra size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Sketch size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SketchUpLayOut size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SketchUpMake size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SketchUpStyleBuilder size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Slash size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SmartOS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SmartOSAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Snapcraft size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Snort size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Snowpack size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Snyk size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Solidarity size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Solidity size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Sophia size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Sorbet size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Source size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Spacemacs size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Spacengine size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Spray size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SquareSpace size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Stan size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Stata size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.StdlibJS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Stencil size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Stitches size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Storybook size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Storyist size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Strings size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Stylable size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.StyledComponents size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Stylelint size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.StylishHaskell size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Stylus size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.StylusOrb size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.StylusS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Sublime size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SuperCollider size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Svelte size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Swagger size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.SystemVerilog size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TFS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TLAPlus size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TOML size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TOTVS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TSX size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TSXAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TTCN3 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TXL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Tag size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Tailwind size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Tcl size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Telegram size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TemplateToolkit size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TempleOS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Terminal size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Tern size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Terraform size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Terser size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TestCafe size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TestCoffeeScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TestDirectory size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TestGeneric size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TestGo size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TestHaskell size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TestJS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TestPerl size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TestPython size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TestReact size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TestRuby size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TestRust size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TestTypeScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TextMate size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Textile size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Thor size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Tilt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TinyMCE size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Tipe size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Tmux size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TortoiseSVN size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Truffle size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Turing size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Twig size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Twine size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TypeDoc size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TypeScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.TypeScriptAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Typings size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.UFO size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.UNO size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Unibeautify size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Unicode size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.UnrealScript size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.UrWeb size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.V size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.V8 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.V8Turbofan size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.VAX size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.VCL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.VHDL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.VMware size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.VRay size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.VSCode size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.VSTS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Vagrant size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Vala size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Velocity size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Verilog size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.VertexShader size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Video size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.VirtualBox size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.VirtualBoxAlt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Vite size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Vue size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Vyper size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.W3C size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.WASI size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.WDL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Wallaby size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Walt size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.WarcraftIII size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Watchman size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.WebAssembly size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.WebGL size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.WebVTT size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Webhint size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Webpack size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.WebpackOld size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Wenyan size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Wercker size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Wget size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.WiX size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.WinUI size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Windi size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Wine size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Wolfram size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Workbox size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Wurst size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.X10 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.XMOS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.XPages size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Xamarin size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Xmake size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Xtend size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Xubuntu size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.YAML size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.YAMLAlt1 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.YAMLAlt2 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.YAMLAlt3 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.YAMLAlt4 size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.YAMLLint size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.YANG size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.YARA size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.YUI size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Yandex size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Yarn size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Yasm size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Yorick size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ZBrush size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Zeit size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Zephir size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Zig size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Zilog size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Zimpl size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.ZorinOS size="40" class="m-0.5" color={random_hex_color_code()} />
  <Icon.Zork size="40" class="m-0.5" color={random_hex_color_code()} />
</div>

<svelte:head>
  <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" />
</svelte:head>
